                                                             Suyash Tambe 

                                                              22070126117

                                                               AIML B2

Experiment 1

In [ ]:
import numpy as np

In [ ]:
def matrix_sum(matrix1, matrix2):
    if matrix1.shape != matrix2.shape:
        raise ValueError("Matrices must have the same dimensions for addition.")

    return matrix1 + matrix2


matrix_a = np.array([[1, 1], [2, 4]])
matrix_b = np.array([[1, 1], [1, 1]])

try:
    result = matrix_sum(matrix_a, matrix_b)
    print("Sum of the matrix:")
    print(result)
except ValueError as e:
    print("Error:", e)


Sum of the matrix:
[[2 2]
 [3 5]]


Experiment 2

In [ ]:
def matrix_difference(matrix1, matrix2):
    if matrix1.shape != matrix2.shape:
        raise ValueError("Matrices must have the same dimensions for addition.")

    return matrix1 - matrix2


matrix_a = np.array([[1, 1], [2, 4]])
matrix_b = np.array([[1, 1], [1, 1]])

try:
    result = matrix_difference(matrix_a, matrix_b)
    print("Sum of the matrix:")
    print(result)
except ValueError as e:
    print("Error:", e)

Sum of the matrix:
[[0 0]
 [1 3]]


Experiment 3

In [ ]:
def matrix_transpose(matrix):
    return np.transpose(matrix)

matrix_a = np.array([[1, 2, 3], [4, 5, 6]])

transposed_matrix = matrix_transpose(matrix_a)

print("Original Matrix:")
print(matrix_a)

print("\nTransposed Matrix:")
print(transposed_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]]

Transposed Matrix:
[[1 4]
 [2 5]
 [3 6]]


Experiment 4

In [ ]:
import numpy as np

def identity_matrix(n):
    return np.eye(n)


n = 4

identity_matrix_5x5 = identity_matrix(n)
print(identity_matrix_5x5)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Experiment 5

In [ ]:
def eigenvalues_and_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

matrix_a = np.array([[1, 2], [3, 4]])

eigenvalues, eigenvectors = eigenvalues_and_eigenvectors(matrix_a)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[-0.37228132  5.37228132]

Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Experiment 6

In [ ]:
def l2_norm(vector):
    return np.linalg.norm(vector)

array_a = np.array([6, 8])

l2_norm_result = l2_norm(array_a)

print("L2 Norm of the array:", l2_norm_result)


L2 Norm of the array: 10.0


Experiment 7

In [ ]:
def frobenius_norm(matrix):
    return np.linalg.norm(matrix, ord='fro')

matrix_a = np.array([[1, 2], [3, 4], [5, 6]])

frobenius_norm_result = frobenius_norm(matrix_a)

print("Frobenius Norm of the matrix is:", frobenius_norm_result)


Frobenius Norm of the matrix is: 9.539392014169456


Experiment8

In [ ]:
def normalize_vector(vector):
    norm = np.linalg.norm(vector)
    if norm == 0:
        raise ValueError("Cannot normalize a zero-vector.")
    return vector / norm

array_a = np.array([3, 4])

normalized_vector = normalize_vector(array_a)

print("Normalized vector:", normalized_vector)


Normalized vector: [0.6 0.8]


Experiment 9

In [ ]:
def condition_number(matrix):
    matrix_norm = np.linalg.norm(matrix, ord='fro')
    matrix_inverse = np.linalg.inv(matrix)
    inverse_norm = np.linalg.norm(matrix_inverse, ord='fro')

    if matrix_norm == 0.0 or inverse_norm == 0.0:
        raise ValueError("Matrix is singular, and its condition number is undefined.")

    return matrix_norm * inverse_norm

matrix_a = np.array([[1, 2], [3, 4]])

condition_number_result = condition_number(matrix_a)

print("Condition number of the matrix is:", condition_number_result)


Condition number of the matrix is: 14.999999999999998


Experiment 10

In [ ]:
def angle_between_vectors(vector1, vector2):
    dot_product = np.dot(vector1, vector2)
    magnitude1 = np.linalg.norm(vector1)
    magnitude2 = np.linalg.norm(vector2)

    if magnitude1 == 0.0 or magnitude2 == 0.0:
        raise ValueError("Cannot calculate the angle for zero-vectors.")

    cosine_theta = dot_product / (magnitude1 * magnitude2)
    angle_rad = np.arccos(cosine_theta)
    angle_deg = np.degrees(angle_rad)

    return angle_deg

vector_a = np.array([3, 4])
vector_b = np.array([1, 2])

angle_degrees = angle_between_vectors(vector_a, vector_b)

print("Angle between the vectors (in degrees) is:", angle_degrees)


Angle between the vectors (in degrees) is: 10.304846468766044
