In [6]:
import numpy as np

# Compute the Euclidean norm of a vector
a = np.array([1, 2, 3])
b=np.array([10,11,12])
euclidean_norm = np.linalg.norm(a)
print("Euclidean Distance a:", euclidean_norm)

# Compute the L1 norm (Manhattan norm) of a vector
l1_norm = np.linalg.norm(a, ord=1)
print("L1 Norm:", l1_norm)

# Compute the L2 norm (Euclidean norm) of a matrix
matrix = np.array([[1, 2],[3,4]])
l2_norm = np.linalg.norm(matrix)
print("L2 Norm:", l2_norm)


Euclidean Distance a: 3.7416573867739413
L1 Norm: 6.0
L2 Norm: 5.477225575051661


In [2]:
from scipy.spatial import distance
import numpy as np

# Compute the Euclidean distance between two points
point1 = np.array([1, 2, 3])
point2 = np.array([4, 5, 6])
euclidean_distance = distance.euclidean(point1, point2)
print("Euclidean Distance:", euclidean_distance)

Euclidean Distance: 5.196152422706632


In [3]:
# Compute the Manhattan distance between two points
manhattan_distance = distance.cityblock(point1, point2)
print("Manhattan Distance:", manhattan_distance)

Manhattan Distance: 9


In [4]:
# Compute the cosine distance between two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
cosine_distance = distance.cosine(vector1, vector2)
print("Cosine Distance:", cosine_distance)

Cosine Distance: 0.0253681538029239


In [5]:
import numpy as np

# Define two vectors
vector1 = np.array([0.8,0.6,0.3,0.1])
vector2 = np.array([0.7,0.3,0.7,-0.9])

# Compute the dot product of the vectors
dot_product = np.dot(vector1, vector2)

# Compute the magnitudes of the vectors
magnitude1 = np.linalg.norm(vector1)
magnitude2 = np.linalg.norm(vector2)

# Compute the cosine similarity
cosine_similarity = dot_product / (magnitude1 * magnitude2)

print("Cosine Similarity:", cosine_similarity)
cosine_distance = distance.cosine(vector1, vector2)
print("Cosine Distance:", cosine_distance)

Cosine Similarity: 0.598030293637636
Cosine Distance: 0.40196970636236395


In [6]:
import numpy as np
data1=np.random.randint(60,300,size=(100,1)) #Blood glucose
data2=np.random.randint(60,200,size=(100,1)) #Blood pressure

In [7]:
features=np.concatenate((data1,data2),axis=1)
print(features.shape)

(100, 2)


In [8]:
label=np.random.randint(0,2,size=(100,1))

In [9]:
overall_data=np.concatenate((features,label),axis=1)
print(overall_data)

[[ 91 165   0]
 [ 97 133   1]
 [261 113   0]
 [192 115   1]
 [153  65   0]
 [230 109   0]
 [298 170   0]
 [218 146   1]
 [296  78   1]
 [278 102   1]
 [ 81  60   0]
 [158 111   1]
 [ 90 149   1]
 [176 193   0]
 [151 118   1]
 [ 75  81   1]
 [136 146   1]
 [169 125   1]
 [173 194   1]
 [106  87   1]
 [264 143   1]
 [242  96   0]
 [233 156   0]
 [177 178   0]
 [249 172   0]
 [191 174   0]
 [ 82 172   0]
 [136  78   1]
 [129  66   1]
 [120  74   1]
 [261 110   0]
 [194  82   1]
 [ 63 134   1]
 [ 65 128   0]
 [189  89   1]
 [182 156   1]
 [ 99 137   1]
 [211 177   1]
 [264 167   0]
 [177 172   0]
 [119  95   1]
 [240 141   0]
 [ 90  67   0]
 [168  80   1]
 [224 162   1]
 [ 70  73   1]
 [147 199   0]
 [150 105   1]
 [133  77   1]
 [256 143   0]
 [ 65 123   1]
 [204 192   1]
 [271 133   0]
 [235 105   0]
 [ 82 169   1]
 [214 161   1]
 [250 110   1]
 [110  93   1]
 [179 147   1]
 [196 137   1]
 [174 105   1]
 [ 61 179   0]
 [186 135   1]
 [ 65  71   0]
 [239  63   0]
 [163 163   1]
 [206 103 

In [10]:
test_vector=np.random.randint(60,300,size=(1,2))
#detect
#Initialize distance as an empty list
dist=[]
for i in range(features.shape[0]):
      dist.append(np.linalg.norm(test_vector-features[i,:]))

In [11]:
dist=np.array(dist)
sorted_dist=np.sort(dist)

In [12]:
print(dist)

[106.88779163  77.49193506 197.25364382 132.91350571  82.15229759
 166.37908522 252.24789395 170.30854353 225.71885167 211.21789697
  10.         100.84641788  91.00549434 169.45205812  98.81295462
  21.37755833 107.80074211 117.59676866 168.40427548  44.20407221
 210.09045671 174.74839055 188.30825792 158.61904047 210.30454108
 165.51737069 112.53888217  67.44627492  58.30951895  50.96076922
 196.46882704 124.95199078  74.43117626  68.26419266 121.51131635
 146.7548977   81.93289938 182.45273361 220.67623343 154.20765221
  59.40538696 187.40864441  20.24845673  99.0403958  183.88311505
  13.03840481 158.42032698  90.91754506  64.28841264 202.76587484
  63.28506933 187.38463117 212.90608258 170.06175349 109.55363983
 175.071414   185.85209173  51.0881591  138.68309198 146.81280598
 112.40106761 119.41942891 137.29530218  12.52996409 168.02678358
 138.10503249 141.68274419 231.81242417 125.22779244 143.73586887
 196.40010183 103.04368006 152.20052562 212.200377     3.60555128
 209.91426

In [13]:
a=0
for i in range(len(dist)):
  if sorted_dist[0]==dist[i]:
    a=i
    break

print("the result: ",label[a])
print(a)

the result:  [0]
74
