In [1]:
import nltk, warnings, string
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
warnings.filterwarnings("ignore")
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [2]:
#TF-IDF is defined as calculation of how relevant a word in a series or corpus is to a text.
#TF: In a document d, the frequecny represents the number of instances of a given word t.

"""
tf=(count of t in d)/(number of words in d)
idf= Inverse Document Frequency and is defined as number of documents in the corpus separated by
the frequency of the text.
idf=N/(df(t))
N=number of documents containing the term t.
df(t)=document frequency of term t.
"""

'\ntf=(count of t in d)/(number of words in d)\nidf= Inverse Document Frequency and is defined as number of documents in the corpus separated by\nthe frequency of the text.\nidf=N/(df(t))\nN=number of documents containing the term t.\ndf(t)=document frequency of term t.\n'

In [3]:
df=pd.read_csv(r"C:\Users\Suyash Tambe\Desktop\New folder\Twitter_Data.csv")
df.head()

clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [4]:
df.shape

(162980, 2)

In [5]:
df=df.iloc[:100000,:]

In [6]:
df.dropna(inplace=True)

In [7]:
df.category.replace([-1.0,0.0,1.0],["Negative","Neutral","Positive"],inplace=True)

In [8]:
X=df.clean_text.to_numpy()
y=df.category.to_numpy()

In [9]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [10]:
X_train=X[:60000,]
X_val=X[60000:80000,]
X_test=X[80000:,]

y_train=y[:60000,]
y_val=y[60000:80000,]
y_test=y[80000:,]

In [11]:
len(y_test)

19999

In [12]:
tfidf=TfidfVectorizer()
X_train_vect=tfidf.fit_transform(X_train)
X_val_vect=tfidf.transform(X_val)
X_test_vect=tfidf.transform(X_test)

In [13]:
X_train_vect.shape

(60000, 55449)

In [14]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_vect,y_train)

KNeighborsClassifier()

In [15]:
knn_pred=knn.predict(X_test_vect)
print(confusion_matrix(y_test,knn_pred))
print(classification_report(y_test,knn_pred))
accuracy=accuracy_score(y_test,knn_pred)

[[ 808 3147  281]
 [ 242 6243  378]
 [ 434 6054 2412]]
              precision    recall  f1-score   support

    Negative       0.54      0.19      0.28      4236
     Neutral       0.40      0.91      0.56      6863
    Positive       0.79      0.27      0.40      8900

    accuracy                           0.47     19999
   macro avg       0.58      0.46      0.42     19999
weighted avg       0.60      0.47      0.43     19999

